# Workflow for verifying bikeshed documents processing

name: Verify processing
on:
  # only concerned with gating PRs to the main branch
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.2.0

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install bikeshed
        run: |
          pipx install bikeshed
          bikeshed update

      - name: run bikeshed
        run: |
          bikeshed spec proposals/specification/index.bs
          bikeshed spec proposals/primer/application.bs
          bikeshed spec proposals/primer/authorization-agent.bs

      - name: generate svg
        run: for diagram in proposals/*/diagrams/*.seq.mmd; do docker run --rm -v "$PWD:/data" minlag/mermaid-cli -i /data/$diagram; done

      - name: generate png
        run: for diagram in proposals/*/diagrams/*.flow.mmd; do docker run --rm -v "$PWD:/data" minlag/mermaid-cli -i /data/$diagram -o /data/$diagram.png; done
